blank_issues_enabled: false
contact_links:
    - name: â“ Questions & General Discussions
      url: https://github.com/ReFi-Starter/swipe-pad/discussions
      about: Please ask and answer questions here, or start a general discussion.
    - name: ğŸ’¡ Feature Idea (Discussion First)
      url: https://github.com/ReFi-Starter/swipe-pad/discussions/new?category=ideas
      about: Have an idea for a new feature? Please discuss it here first!
